[package]
authors = ["Benno Fünfstück <benno.fuenfstueck@gmail.com>"]
name = "nix-index"
version = "0.1.0"

[[bin]]
doc = false
name = "nix-index"

[[bin]]
name = "nix-locate"

[dependencies]
ansi_term = "0.9.0"
bincode = "0.8.0"
brotli2 = "0.3.0"
byteorder = "1.0.0"
clap = "2.20.5"
error-chain = "0.10.0"
futures = "0.1.10"
grep = "0.1.5"
hyper = "0.11"
isatty = "0.1.3"
memchr = "1.0.1"
ordermap = "0.2.8"
regex = "0.2.1"
regex-syntax = "0.4.0"
separator = "0.3.1"
serde = "1.0.10"
serde_bytes = "0.10.1"
serde_derive = "1.0.10"
serde_json = "1.0.2"
stderr = "0.7.0"
tokio-core = "0.1.4"
tokio-retry = "0.1.0"
tokio-timer = "0.1.0"
void = "1.0.2"
xdg = "2.0.0"
xml-rs = "0.4.1"
xz2 = "0.1.2"
zstd = "0.4.3"

[[example]]
name = "nix-index-debug"

[profile]

[profile.release]
debug = true
