[package]
authors = ["Benno Fünfstück <benno.fuenfstueck@gmail.com>"]
edition = "2021"
name = "nix-index"
version = "0.1.3"
[[bin]]
doc = false
name = "nix-index"

[[bin]]
name = "nix-locate"

[dependencies]
ansi_term = "0.12.1"
bincode = "1.3.3"
brotli2 = "0.3.2"
byteorder = "1.4.3"
error-chain = "0.12.4"
futures = "0.3.25"
grep = "0.2.11"
headers = "0.3.8"
http = "0.2.8"
hyper-proxy = "0.9.1"
atty = "0.2.14"
memchr = "2.5.0"
num_cpus = "1.15.0"
indexmap = "1.9.2"
regex = "1.7.0"
regex-syntax = "0.6.28"
separator = "0.4.1"
serde = "1.0.152"
serde_bytes = "0.11.8"
serde_derive = "1.0.152"
serde_json = "1.0.91"
tokio-retry = "0.3.0"
tokio-stream = "0.1.11"
url = "2.3.1"
void = "1.0.2"
xdg = "2.4.1"
xml-rs = "0.8.4"
xz2 = "0.1.7"
zstd = { version = "0.9.2", features = [ "zstdmt" ] }

[dependencies.hyper]
features = ["client", "http1", "http2", "runtime", "stream"]
version = "0.14.23"

[dependencies.tokio]
features = ["full"]
version = "1.24.1"

[dependencies.clap]
version = "3.2.23"
features = ["derive"]

[[example]]
name = "nix-index-debug"

[profile]
[profile.release]
debug = true
