[package]
authors = ["Benno Fünfstück <benno.fuenfstueck@gmail.com>"]
edition = "2018"
name = "nix-index"
version = "0.1.3"
[[bin]]
doc = false
name = "nix-index"

[[bin]]
name = "nix-locate"

[dependencies]
ansi_term = "0.12.1"
bincode = "1.3.3"
brotli2 = "0.3.2"
byteorder = "1.4.3"
clap = "2.33.3"
error-chain = "0.12.4"
futures = "0.3.17"
grep = "0.2.8"
headers = "0.3.5"
http = "0.2.5"
hyper-proxy = "0.9.1"
atty = "0.2.14"
memchr = "2.4.1"
num_cpus = "1.13.0"
indexmap = "1.7.0"
regex = "1.5.4"
regex-syntax = "0.6.25"
separator = "0.4.1"
serde = "1.0.130"
serde_bytes = "0.11.5"
serde_derive = "1.0.130"
serde_json = "1.0.71"
stderr = "0.8.0"
tokio-retry = "0.3.0"
tokio-stream = "0.1.8"
url = "2.2.2"
void = "1.0.2"
xdg = "2.4.0"
xml-rs = "0.8.4"
xz2 = "0.1.6"
zstd = { version = "0.9.0", features = [ "zstdmt" ] }

[dependencies.hyper]
features = ["client", "http1", "http2", "runtime", "stream"]
version = "0.14.15"

[dependencies.tokio]
features = ["full"]
version = "1.14.0"

[[example]]
name = "nix-index-debug"

[profile]
[profile.release]
debug = true
